### ISSUE TITLE
 Identity Integration

### ISSUE THREAD

**Issue by BharathRam125** [BharathRam125/Bulky#3]
#### Description:
When scaffolding Identity in a .NET Core project, there are several tasks and considerations that need to be addressed for seamless integration.

#### Tasks:
- [x] **Scaffolding Error**
- [x] **Scaffold Identity Issue (NET8)**
- [x] **Understand what Got Added**
- [x] **Add Identity Tables**
- [x] **Extend Identity User**
- [x] **Register a User**
- [x] **Register an Application User**
- [x] **Create Roles in Database**
- [x] **Assign Roles on Registration**
- [x] **Authorization in Project**
- [x] **Update Login and Register UI**
- [x] **Register Other Fields**
- [x] **UI Bug**
