### ISSUE TITLE
Company CRUD Operations

### ISSUE THREAD

**Issue by BharathRam125** [BharathRam125/Bulky#4]
#### Description:
Implement CRUD operations for managing company data in the application.

#### Tasks:
- [ ] **Company CRUD Operations**
- [ ] **Display Company Dropdown**
- [ ] **Toggle Company Dropdown**
- [ ] **Register Company User**
