### ISSUE TITLE
Shopping Cart Implementation

### ISSUE THREAD

**Issue by BharathRam125** [BharathRam125/Bulky#5]
#### Description:
Implement a shopping cart feature in the application to enable users to add and manage items for purchase.

#### Tasks:
- [ ] **Add Shopping Cart Model**
- [ ] **Add Shopping Cart to Repository**
- [ ] **Add ApplicationUser Repository**
- [ ] **Define Model for Details Page**
- [ ] **Add to Cart**
- [ ] **Fix Issue with Add to Cart**
- [ ] **Resolve A Weird Bug**
- [ ] **Shopping Cart UI**
- [ ] **Retrieve Shopping Cart**
- [ ] **Calculate Order Total in Shopping Cart**
- [ ] **Implement Dynamic Shopping Cart**
- [ ] **Update Quantity in Shopping Cart**
- [ ] **Design Order Summary UI**
