### ISSUE TITLE
 Order Confirmation and Payment Integration

### ISSUE THREAD

**Issue by BharathRam125** [BharathRam125/Bulky#6]
#### Description:
Implement functionality to confirm orders and integrate payment processing using Stripe.

#### Tasks:
- [ ] **Create Order Header and Details Model**
- [ ] **Add Order Header and Detail Repository**
- [ ] **Enhance ShoppingCartVM for Dynamic Behavior**
- [ ] **Implement Summary GET Action Method**
- [ ] **Load Summary UI with Data**
- [ ] **Implement Order Status**
- [ ] **Implement Summary POST Action**
- [ ] **Implement Place Order for Company Accounts**
- [ ] **Register for Stripe Account**
- [ ] **Configure Stripe in Project**
- [ ] **Add Helper Methods in Order Header Repository**
- [ ] **Integrate Stripe Payment**
- [ ] **Confirm Stripe Payment**
- [ ] **Handle Order Placed Successfully with Stripe**
